
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  fmt:
    name: Check simple example
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
      with:
        target: x86_64-apple-ios
    - uses: taiki-e/install-action@v2
      with:
        tool: cargo-dinghy@0.6.8
    - name: boot iOS simulator
      run: |
        xcrun simctl boot "$(xcrun simctl list devices 'iOS' --json | jq '.devices | with_entries( select(.key|contains("iOS"))) | .[] | [ .[].name ] | map( select(contains("iPhone")) ) | sort | .[0] ' | jq -r)"
    - name: run accelerometer example
      run: cargo run --example accelerometer --target x86_64-apple-ios
